### ISSUE TITLE
Boss, silly question pls

### ISSUE THREAD

**Issue by ben-haim** [Kunstmaan/hands-on-with-multichain#2]
I hope you are well.... \o/
Can you give a quickly help on php library, im trying to interact with api...

This is my details and works fine :+1: 
curl -i -X POST -d '{"method":"getinfo"}' http://multichainrpc:password@0.0.0.0:8081

It doesn't work :-1:  Any clue pls ?
$client = new MultichainClient("http://0.0.0.0:8081", 'multichainrpc', 'password', 3);

error:

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to JsonRPC\Client::__construct() must be an instance of JsonRPC\HttpClient, array given, called in /src/hands-on-with-multichain/vendor/kunstmaan/libphp-multichain/src/be/kunstmaan/multichain/MultichainClient.php on line 49 and defined in /src/hands-on-with-multichain/vendor/fguillot/json-rpc/src/JsonRPC/Client.php:66

Stack trace:
#0 /src/hands-on-with-multichain/vendor/kunstmaan/libphp-multichain/src/be/kunstmaan/multichain/MultichainClient.php(49): JsonRPC\Client->__construct(http://localhost:8081', 'multichainrpc', 'password', 3, Array)
#1 /src/hands-on-with-multichain/src/Multichain/Console/Shared/MultichainCommands.php(23): be\kunstmaan\multichain\MultichainClient->__construct('http://localhost:8081', 'multichainrpc', 'password', 3)
#2 /src/hands-on-with-multichain/src/Multichain/Console/Command/CreateAddressCommand.php(31): Multichain\Console\Command\CreateAddressCommand->connectMultichain()
#3 /src/hands-on-with-multichain/vendor/symfony/console/Command/Command.php(256): Multichain\Console\Command in /src/hands-on-with-multichain/vendor/fguillot/json-rpc/src/JsonRPC/Client.php on line 66

Best Regards,

:-)

**Comment by ben-haim** [comment]
Boss ?
